In [1]:
import pandas as pd

In [2]:
df = pd.read_csv("../data/pedidos.csv")

df.head()

,pedido_id,data_pedido,horario_pedido,restaurante,categoria,cidade,valor_pedido,tempo_entrega_min,avaliacao,metodo_pagamento,status
0,1,2026-06-13,11:01,Cantinho da Massa,Massas,Eusébio,55.71,62.0,1.0,Cartão de crédito,Entregue
1,2,2026-01-09,10:05,Sushi Fortaleza,Sushi,Eusébio,100.86,16.0,5.0,Cartão de débito,Entregue
2,3,2026-06-29,18:26,Sushi Fortaleza,Sushi,Maracanaú,114.28,66.0,1.0,Cartão de débito,Entregue
3,4,2026-03-29,14:09,Sushi Fortaleza,Sushi,Caucaia,36.35,39.0,1.0,Pix,Entregue
4,5,2026-06-04,14:51,Sabor Nordestino,Brasileira,Maracanaú,105.80,39.0,1.0,Pix,Entregue

In [3]:
df.shape

(5003, 11)

In [4]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 5003 entries, 0 to 5002
Data columns (total 11 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   pedido_id          5003 non-null   int64
 1   data_pedido        5003 non-null   str
 2   horario_pedido     5003 non-null   str
 3   restaurante        5003 non-null   str
 4   categoria          5003 non-null   str
 5   cidade             5002 non-null   str
 6   valor_pedido       5003 non-null   float64
 7   tempo_entrega_min  5002 non-null   float64
 8   avaliacao          5002 non-null   float64
 9   metodo_pagamento   5003 non-null   str
 10  status             5003 non-null   str
dtypes: float64(3), int64(1), str(7)
memory usage: 754.3 KB

In [5]:
df.isnull().sum()

pedido_id            0
data_pedido          0
horario_pedido       0
restaurante          0
categoria            0
cidade               1
valor_pedido         0
tempo_entrega_min    1
avaliacao            1
metodo_pagamento     0
status               0
dtype: int64

In [6]:
df.duplicated().sum()

np.int64(3)

In [7]:
df[df.isnull().any(axis=1)]

,pedido_id,data_pedido,horario_pedido,restaurante,categoria,cidade,valor_pedido,tempo_entrega_min,avaliacao,metodo_pagamento,status
100,101,2026-02-02,18:37,Churrasco & Cia,Churrasco,Fortaleza,159.87,43.0,NaN,Dinheiro,Entregue
250,251,2026-05-01,22:53,Churrasco & Cia,Churrasco,Eusébio,79.31,NaN,1.0,Cartão de débito,Entregue
400,401,2026-04-16,10:55,Burger House,Hambúrguer,NaN,178.78,36.0,4.0,Dinheiro,Entregue

In [8]:
df[df.duplicated(keep=False)].sort_values("pedido_id")

,pedido_id,data_pedido,horario_pedido,restaurante,categoria,cidade,valor_pedido,tempo_entrega_min,avaliacao,metodo_pagamento,status
50,51,2026-01-19,17:26,Sushi Fortaleza,Sushi,Maracanaú,99.10,30.0,2.0,Cartão de crédito,Entregue
5000,51,2026-01-19,17:26,Sushi Fortaleza,Sushi,Maracanaú,99.10,30.0,2.0,Cartão de crédito,Entregue
150,151,2026-03-15,11:41,Pizza Express,Pizza,Maracanaú,94.03,50.0,1.0,Dinheiro,Entregue
5001,151,2026-03-15,11:41,Pizza Express,Pizza,Maracanaú,94.03,50.0,1.0,Dinheiro,Entregue
300,301,2026-05-17,14:38,Burger House,Hambúrguer,Caucaia,176.64,33.0,3.0,Pix,Cancelado
5002,301,2026-05-17,14:38,Burger House,Hambúrguer,Caucaia,176.64,33.0,3.0,Pix,Cancelado